SITE_TITLE: Tyler Butler
SITE_AUTHOR: Tyler Butler
HOME_URL: '/'
PERMALINK_STYLE: pretty

FEED_URL: 'http://feeds.feedburner.com/TylerButlerAllPosts'

THEME_SETTINGS:
  typekit_id: vty2qol
  twitter_id: tylerbutler
  tweet_count: 4
  comments: disqus
  comments_account: tylerbutlercom

POST_TIMEZONE: 'America/Los_Angeles'

POST_RENAME_CONFIG:
  draft: '{slug} [{status}].md'
