SITE_TITLE: Tyler Butler
SITE_AUTHOR: Tyler Butler
HOME_URL: '/'
PERMALINK_STYLE: pretty

FEED_FULL_CONTENT: yes

THEME_SETTINGS:
  typekit_id: vty2qol
  comments: disqus
  comments_account: tylerbutlercom

POST_TIMEZONE: 'America/Los_Angeles'

POST_RENAME_ENABLED: yes
POST_RENAME_CONFIG:
  draft: '{slug} [{status}].md'
  review: '({status}) {slug}.md'
METADATA_FORMAT: fenced
