SUPER: base.yaml

SITE_URL: 'http://localhost:8000'
POST_DIR:
- 'C:\Users\Tyler\Drop Box\Engineer\tylerbutler.com'
- 'C:\Users\Tyler\Drop Box\Engineer\tylerbutler.com\Published'

DEBUG: yes
PUBLISH_DRAFTS: no
PUBLISH_PENDING: yes
PUBLISH_REVIEW: yes

SERVER_TIMEZONE: 'America/Los_Angeles'
COMPRESSOR_ENABLED: no
PREPROCESS_LESS: yes
