SUPER: base.yaml

SITE_URL: 'http://localhost:8000'
OUTPUT_DIR: './output/local'

DEBUG: yes
PUBLISH_DRAFTS: no
PUBLISH_PENDING: yes
PUBLISH_REVIEW: yes

SERVER_TIMEZONE: 'America/Los_Angeles'
COMPRESSOR_ENABLED: no
PREPROCESS_LESS: yes
